### ISSUE TITLE
[question] littele question

### ISSUE THREAD

**Issue by master-davidlee** [PureStake/crowdloan-tools#16]
Hi, I'm wondering if the order of contributors in the result JSON file gets from the contribution_getter.ts is the same as the order in which they participated in the crowd loan. The first user in the document is the first to participate in the crowd loan and the second user is the second to participate in the crowd loan. and so on

**Comment by master-davidlee** [comment]
I randomly choose some accounts and check out the time order, they are not ordered in time.  Is there any way I can order them in participant time?

**Comment by girazoki** [comment]
The script takes the information form storage, so I dont think that is possible with this approach. There is another approach which is take the contributions from subscan, and that could be ordered by time

**Comment by master-davidlee** [comment]
I just look around subscan. Do you mean there is existing approach to get contributions from subscan. Or I need to write by my self

**Comment by girazoki** [comment]
you need to write it yourself

**Comment by master-davidlee** [comment]
Ok thanks
